# Generated by Django 5.0.6 on 2024-05-16 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('round_number', models.IntegerField()),
                ('right_team_goals_scored', models.PositiveSmallIntegerField(default=0)),
                ('left_team_goals_scored', models.PositiveSmallIntegerField(default=0)),
                ('drafter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafted_fixtures', to='stats.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='stats.season')),
                ('left_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='left_team_fixtures', to='stats.team')),
                ('right_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='right_team_fixtures', to='stats.team')),
                ('winner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='stats.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveSmallIntegerField(default=0)),
                ('goals_scored', models.PositiveSmallIntegerField(default=0)),
                ('mvp_votes_received', models.PositiveSmallIntegerField(default=0)),
                ('mvp_count', models.PositiveSmallIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='stats.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_stats', to='stats.season')),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
        migrations.CreateModel(
            name='FixturePlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_scored', models.PositiveSmallIntegerField(default=0)),
                ('mvp_votes_received', models.PositiveSmallIntegerField(default=0)),
                ('mvp', models.BooleanField(default=False)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_stats', to='stats.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures_stats', to='stats.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_stats', to='stats.team')),
            ],
            options={
                'unique_together': {('fixture', 'player')},
            },
        ),
    ]
