# Generated by Django 5.0.6 on 2024-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerSeasonStatistics',
            new_name='SeasonPlayerStatistics',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='left_team_goals_scored',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='right_team_goals_scored',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='winner_team',
        ),
        migrations.AlterField(
            model_name='fixture',
            name='round_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
