# Generated by Django 5.0.6 on 2024-05-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_seasonplayerstatistics_points_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonplayerstatistics',
            name='draws',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonplayerstatistics',
            name='loses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonplayerstatistics',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
