# Generated by Django 5.0.6 on 2024-05-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_remove_fixture_left_team_remove_fixture_right_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonplayerstatistics',
            old_name='loses',
            new_name='losses',
        ),
        migrations.AddField(
            model_name='fixtureplayerstatistics',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
