# Generated by Django 5.0.6 on 2024-05-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_rename_loses_seasonplayerstatistics_losses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonplayerstatistics',
            name='draws',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='seasonplayerstatistics',
            name='goals_scored',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='seasonplayerstatistics',
            name='losses',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='seasonplayerstatistics',
            name='matches_played',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='seasonplayerstatistics',
            name='mvp_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='seasonplayerstatistics',
            name='mvp_votes_received',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='seasonplayerstatistics',
            name='points_earned',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='seasonplayerstatistics',
            name='wins',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
