# Generated by Django 5.0.6 on 2024-05-19 23:00

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_seasonplayerstatistics_draws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonplayerstatistics',
            name='avg_goals',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='seasonplayerstatistics',
            name='points_pct',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='date',
            field=models.DateField(default=django.db.models.functions.datetime.Now()),
        ),
    ]
