# Generated by Django 5.0.6 on 2024-05-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_seasonplayerstatistics_avg_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonplayerstatistics',
            name='avg_goals',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
