# Generated by Django 5.0.6 on 2024-05-21 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_alter_seasonplayerstatistics_avg_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='goal_balance',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='winner_team',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='fixture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='stats.fixture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='goals_scored',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='round_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
